### ISSUE TITLE
How can we enable Case Insensitive Properties

### ISSUE THREAD

**Issue by MrKevHunter** [djanosik/Moon.OData#4]
Hi,

We can set the `ODataOptions` case sensitive value manually but there does not appear to be a way to set the value if we are using the built in Model Binding. 

Is there something I am missing?

**Comment by djanosik** [comment]
You can still set the `IsCaseSensitive` property before you touch any of OData properties.

**Comment by MrKevHunter** [comment]
Hi,

I don't think I explained myself very well, or perhaps I am missing something.

If I use the sample in the repo hitting the controller with 

`http://localhost:58334/?$filter=Id eq 1` 

works fine as I would expect, if I use

`http://localhost:58334/?$filter=ID eq 1`

then I get

```	
$exception	"Could not find a property named 'ID' on type 'Moon.AspNetCore.OData.Sample.Entity'."	Microsoft.OData.ODataException
```

with the stack trace 

```
   at Microsoft.OData.UriParser.EndPathBinder.GeneratePropertyAccessQueryForOpenType(EndPathToken endPathToken, SingleValueNode parentNode)
   at Microsoft.OData.UriParser.EndPathBinder.BindEndPath(EndPathToken endPathToken)
   at Microsoft.OData.UriParser.MetadataBinder.Bind(QueryToken token)
   at Microsoft.OData.UriParser.BinaryOperatorBinder.GetOperandFromToken(BinaryOperatorKind operatorKind, QueryToken queryToken)
   at Microsoft.OData.UriParser.BinaryOperatorBinder.BindBinaryOperator(BinaryOperatorToken binaryOperatorToken)
   at Microsoft.OData.UriParser.MetadataBinder.Bind(QueryToken token)
   at Microsoft.OData.UriParser.FilterBinder.BindFilter(QueryToken filter)
   at Microsoft.OData.UriParser.ODataQueryOptionParser.ParseFilterImplementation(String filter, ODataUriParserConfiguration configuration, ODataPathInfo odataPathInfo)
   at Microsoft.OData.UriParser.ODataQueryOptionParser.ParseFilter()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.CreateValue()
   ```

I think this takes place in the model binding 

if I add 
```
Type type = model.GetType();

PropertyInfo prop = type.GetProperty("IsCaseSensitive");

prop.SetValue(model, false, null);
```

to the BindModelAsync function than it works as expected.

I'm happy to submit a PR with some neater code.

Lastly thanks for a great project and your help so far.

**Comment by djanosik** [comment]
I see now. ASP.NET checks values of all properties when model binding happens. I will accept the PR, thank you!

**Comment by MrKevHunter** [comment]
Cheers, PR created #5 
let me know if it needs any changes

**Comment by MrKevHunter** [comment]
The PR you merged should have fixed this now
